name: "Run a Drupal 8+ script"
description: 'SSH to server and execute Drush update commands on the Drupal 8+ instance'
inputs:
  path:
    description: 'Absolute path on the server where the instance is located'
    required: true
  server_name:
    description: 'Name of the server SSH name'
    required: true
    default: 'server'
  drush:
    description: 'Path to drush executable'
    required: false
    default: './vendor/bin/drush'
  script_path:
    description: 'Path to drush executable'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Run drupal script using drush"
      shell: bash
      run: |
        ssh ${{ inputs.server_name }} 'cd ${{ inputs.path }} && ${{ inputs.drush }} scr ${{ inputs.script_path }}'
